# Generated by Django 4.2.7 on 2023-12-03 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='number',
        ),
    ]
