# Generated by Django 4.2.7 on 2023-12-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0002_remove_player_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='week',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
