# Generated by Django 4.2.7 on 2023-12-04 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0003_fixture_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='fmx.team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='fmx.team'),
        ),
    ]
