# Generated by Django 4.2.7 on 2023-12-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0004_alter_fixture_away_alter_fixture_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='round',
            field=models.TextField(blank=True, null=True),
        ),
    ]
