# Generated by Django 4.2.7 on 2023-12-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0005_fixture_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='club',
            field=models.TextField(blank=True),
        ),
    ]
