# Generated by Django 4.2.7 on 2023-12-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0006_user_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Initial_budget',
            field=models.FloatField(default=680),
        ),
    ]
