# Generated by Django 4.2.7 on 2023-12-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0007_user_initial_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Initial_budget',
            new_name='initial_budget',
        ),
    ]
