# Generated by Django 4.2.7 on 2023-12-04 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0008_rename_initial_budget_user_initial_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_club',
            name='goalkeeper_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='g1', to='fmx.player'),
        ),
    ]
