# Generated by Django 4.2.7 on 2023-12-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0012_alter_player_value_alter_user_club_attacker_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_club',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
