# Generated by Django 4.2.7 on 2023-12-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0013_alter_user_club_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_club',
            name='total_draw',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_club',
            name='total_lost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_club',
            name='total_won',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
