# Generated by Django 4.2.7 on 2023-12-12 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0014_alter_user_club_total_draw_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.TextField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club', to='fmx.user_club')),
                ('player_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='fmx.player')),
                ('player_10', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p10', to='fmx.player')),
                ('player_11', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p11', to='fmx.player')),
                ('player_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='fmx.player')),
                ('player_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p3', to='fmx.player')),
                ('player_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p4', to='fmx.player')),
                ('player_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p5', to='fmx.player')),
                ('player_6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p6', to='fmx.player')),
                ('player_7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p7', to='fmx.player')),
                ('player_8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p8', to='fmx.player')),
                ('player_9', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p9', to='fmx.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_lineup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
