# Generated by Django 4.2.7 on 2023-12-12 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0016_fixture_round_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture_round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('goals', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('conceded', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('assists', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('yellowcard', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('redcard', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture_ids', to='fmx.fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='fmx.player')),
            ],
        ),
    ]
