# Generated by Django 4.2.7 on 2023-12-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0017_fixture_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture_round',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
