# Generated by Django 4.2.7 on 2023-12-13 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0019_remove_user_club_remove_user_initial_budget_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Club_details',
        ),
    ]
