# Generated by Django 4.2.7 on 2023-12-13 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0020_rename_student_club_details'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fixture_round',
            unique_together={('fixture', 'player')},
        ),
    ]
