# Generated by Django 4.2.7 on 2023-12-13 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0021_alter_fixture_round_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fixture_round',
            unique_together=set(),
        ),
    ]
