# Generated by Django 4.2.7 on 2023-12-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0022_alter_fixture_round_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture_round',
            name='assists',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
