# Generated by Django 4.2.7 on 2023-12-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0023_alter_fixture_round_assists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture_round',
            name='assists',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
