# Generated by Django 4.2.7 on 2023-12-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0024_alter_fixture_round_assists'),
    ]

    operations = [
        migrations.CreateModel(
            name='headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
            ],
        ),
    ]
