# Generated by Django 4.2.7 on 2023-12-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0025_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
