# Generated by Django 4.2.7 on 2023-12-16 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0029_lineup_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_num', models.PositiveIntegerField()),
                ('lineup_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_table1', to='fmx.lineup')),
                ('lineup_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_table2', to='fmx.lineup')),
            ],
        ),
    ]
