# Generated by Django 4.2.7 on 2023-12-16 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0030_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='lineup_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_table1', to='fmx.lineup_round'),
        ),
        migrations.AlterField(
            model_name='table',
            name='lineup_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_table2', to='fmx.lineup_round'),
        ),
    ]
