# Generated by Django 4.2.7 on 2023-12-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0032_table_score_1_table_score_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='elo_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difference', models.PositiveIntegerField(blank=True, null=True)),
                ('probability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
