# Generated by Django 4.2.7 on 2023-12-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0034_club_details_elo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_details',
            name='elo',
            field=models.DecimalField(blank=True, decimal_places=2, default=1000, max_digits=7, null=True),
        ),
    ]
