# Generated by Django 4.2.7 on 2023-12-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0036_alter_table_lineup_1_alter_table_lineup_2'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('lineup_1', 'lineup_2', 'round_num')},
        ),
    ]
