# Generated by Django 4.2.7 on 2023-12-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0037_alter_table_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='next_round',
            field=models.BooleanField(default=False),
        ),
    ]
