# Generated by Django 4.2.7 on 2023-12-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0038_table_next_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='ai',
            field=models.BooleanField(default=False),
        ),
    ]
