# Generated by Django 4.2.7 on 2023-12-20 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0039_lineup_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='squad_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_club1', to='fmx.user_club'),
        ),
        migrations.AddField(
            model_name='table',
            name='squad_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_club2', to='fmx.user_club'),
        ),
    ]
