# Generated by Django 4.2.7 on 2023-12-20 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0040_table_squad_1_table_squad_2'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fixture_round',
            unique_together={('fixture', 'player')},
        ),
    ]
