# Generated by Django 4.2.7 on 2023-12-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0041_alter_fixture_round_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
