# Generated by Django 4.2.7 on 2023-12-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0042_notificationtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationType',
        ),
        migrations.AddField(
            model_name='headline',
            name='type',
            field=models.TextField(default='buy'),
        ),
    ]
