# Generated by Django 4.2.7 on 2023-12-28 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0044_one2one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='one2one',
            name='lineup_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineup_table11', to='fmx.lineup'),
        ),
        migrations.AlterField(
            model_name='one2one',
            name='lineup_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineup_table21', to='fmx.lineup'),
        ),
        migrations.AlterField(
            model_name='one2one',
            name='squad_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_club11', to='fmx.user_club'),
        ),
        migrations.AlterField(
            model_name='one2one',
            name='squad_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_club21', to='fmx.user_club'),
        ),
    ]
