# Generated by Django 4.2.7 on 2023-12-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0045_alter_one2one_lineup_1_alter_one2one_lineup_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='one2one',
            name='round_num',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
