# Generated by Django 4.2.7 on 2023-12-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0046_alter_one2one_round_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='one2one',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('refused', 'Refused'), ('accepted', 'Accepted')], default=1, max_length=12),
            preserve_default=False,
        ),
    ]
