# Generated by Django 4.2.7 on 2024-01-01 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0047_one2one_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tmp_lineup_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('goals', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_score', to='fmx.lineup')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p', to='fmx.player')),
            ],
        ),
    ]
