# Generated by Django 4.2.7 on 2024-01-01 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0049_alter_tmp_lineup_score_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tmp_lineup_score',
            unique_together=set(),
        ),
    ]
