# Generated by Django 4.2.7 on 2024-01-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0051_alter_tmp_lineup_score_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tmp_lineup_score',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tmp_lineup_score',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
