# Generated by Django 4.2.7 on 2024-01-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0052_alter_tmp_lineup_score_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmp_lineup_score',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
