# Generated by Django 4.2.7 on 2024-01-01 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0053_alter_tmp_lineup_score_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmp_lineup_score',
            name='club',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='club_sc', to='fmx.user_club'),
            preserve_default=False,
        ),
    ]
