# Generated by Django 4.2.7 on 2024-01-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0054_tmp_lineup_score_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmp_lineup_score',
            name='match',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tmp_lineup_score',
            name='type',
            field=models.CharField(choices=[('one2one', 'one2one'), ('table', 'table')], default=0, max_length=12),
            preserve_default=False,
        ),
    ]
