# Generated by Django 4.2.7 on 2024-01-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0056_tmp_lineup_score_assists'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmp_lineup_score',
            name='red',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tmp_lineup_score',
            name='yellow',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
