# Generated by Django 4.2.7 on 2024-01-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0057_tmp_lineup_score_red_tmp_lineup_score_yellow'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
