# Generated by Django 4.2.7 on 2024-01-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0060_starter_round_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='original_value',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
