# Generated by Django 4.2.7 on 2024-01-08 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0061_player_original_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='original_value',
            new_name='current_value',
        ),
    ]
