# Generated by Django 4.2.7 on 2024-01-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0063_club_details_has_lineup'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_details',
            name='has_squad',
            field=models.BooleanField(default=False),
        ),
    ]
