# Generated by Django 4.2.7 on 2024-01-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0064_club_details_has_squad'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='formation',
            field=models.TextField(default='442'),
        ),
    ]
