# Generated by Django 4.2.7 on 2024-01-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0065_lineup_formation'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='round_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
