# Generated by Django 4.2.7 on 2024-01-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0067_user_club_attacker_1_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_club',
            name='initial_budget',
            field=models.FloatField(default=800),
        ),
    ]
