# Generated by Django 4.2.7 on 2024-01-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0068_alter_user_club_initial_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_details',
            name='initial_budget',
            field=models.FloatField(default=800),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
