# Generated by Django 4.2.7 on 2024-01-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0070_alter_fixture_round_rating_alter_fixture_round_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmp_lineup_score',
            name='round_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
