# Generated by Django 4.2.7 on 2024-01-23 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0071_tmp_lineup_score_round_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goalscores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveIntegerField()),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goalscorer', to='fmx.player')),
            ],
        ),
    ]
