# Generated by Django 4.2.7 on 2024-02-01 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmx', '0073_matchtick'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lineup_round',
        ),
    ]
